### ISSUE TITLE
confused about the contract

### ISSUE THREAD

**Issue by wangsai-silence** [ChainSecurity/constantinople-reentrancy#4]
Hi, 
I'm a little confused about the attack contract.
constantinople does not change anything on msstore.
So why this can be affected?

**Comment by wangsai-silence** [comment]
> Hi,
> I'm a little confused about the attack contract.
> constantinople does not change anything on msstore.
> So why this can be affected?

I  understand now. Change split will use SSTORE.

**Comment by ritzdorf** [comment]
Yes. That is correct. Any more questions?

**Comment by wangsai-silence** [comment]
> Yes. That is correct. Any more questions?

No. Thanks.

**Comment by rosid86** [comment]
2082235082
